// <auto-generated />
using System;
using Api_Celero.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_Celero.Migrations
{
    [DbContext(typeof(ReciboCajaOfflineContext))]
    [Migration("20250621055833_FinalizeModels")]
    partial class FinalizeModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Api_Celero.Models.ClienteLocal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Closed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VATNr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("eMail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClientesLocales");
                });

            modelBuilder.Entity("Api_Celero.Models.ReciboCajaOffline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CUCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetallesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Pendiente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Person")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefStr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SerNr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RecibosOffline");
                });
#pragma warning restore 612, 618
        }
    }
}
